services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    networks:
      - app-network


  backend:
    image: ${DOCKER_REGISTRY-}backend
    build:
      context: .
      dockerfile: Backend/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__pgdb=Host=postgres;Database=mydatabase;Username=myuser;Password=mypassword
    depends_on:
      - postgres
    networks:
      - app-network
    ports:
      - 7223:8080

  frontend:
    image: ${DOCKER_REGISTRY-}front
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
        - 9084:80
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
