/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AccessTokenResponse {
  accessToken: string | null;
  expiresIn: number;
  refreshToken: string | null;
  tokenType?: string | null;
}
