/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ShipDto } from '../../models/ship-dto';

export interface ApiV1ShipsIdDelete$Json$Params {
  id: number;
}

export function apiV1ShipsIdDelete$Json(http: HttpClient, rootUrl: string, params: ApiV1ShipsIdDelete$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ShipDto>>> {
  const rb = new RequestBuilder(rootUrl, apiV1ShipsIdDelete$Json.PATH, 'delete');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ShipDto>>;
    })
  );
}

apiV1ShipsIdDelete$Json.PATH = '/api/v1/Ships/{id}';
