/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { validatePassword } from '../fn/password-validator-endpoint/validate-password';
import { ValidatePassword$Params } from '../fn/password-validator-endpoint/validate-password';

@Injectable({ providedIn: 'root' })
export class PasswordValidatorEndpointService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `validatePassword()` */
  static readonly ValidatePasswordPath = '/validatePassword';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `validatePassword()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  validatePassword$Response(params: ValidatePassword$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return validatePassword(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `validatePassword$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  validatePassword(params: ValidatePassword$Params, context?: HttpContext): Observable<void> {
    return this.validatePassword$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
